import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Layout.module.scss";
import Head from "next/head";

type LayoutProps = {
  children?: React.ReactNode;
};

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Interaction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <main className={styles.main}>{children}</main>
      {/* <footer className={styles.footer}></footer> */}
    </>
  );
}
